---
title: "GC_BehaviorTO"
author: "Teague O'Mara"
date: "2021-03-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ring-tailed lemur Fecal Glucorticoids

This document brings together GC concentrations with aggression and marking data. First, let's bring in the GC and Aggression & Marking data.

```{r data}
gc <- read_sheet("https://docs.google.com/spreadsheets/d/12j8bzWNEdZ3SdTUqrbkXAa5Sb-JFNn25EkFakMO-G2E/edit?usp=sharing")
aggMark <- read_sheet("https://docs.google.com/spreadsheets/d/1t4rXq04tns6TUvjkL8m5a8mtZsi5SA6bNBLzbrY9zmU/edit?usp=sharing")
```

### Join together data frames
```{r joins}
library(lubridate)

#Reformat dates to play nicely
gc$date <- as.Date(gc$collectionDate)
aggMark$date <- mdy(aggMark$date)

#Change to upper case & take out the period. Maybe these will play nicely together.
aggMark$an.id <- toupper(aggMark$an.id)
gc$an.id <- toupper(gc$an.id)
aggMark$an.id <- str_replace_all(aggMark$an.id, "\\.", "")

gcBehav <- aggMark %>% left_join(gc, by =c("an.id", "date"))
#gcBehav has 1499 obs, aggMark has 1417. There were dates in the gc data not in the aggMark data.

```


